# Generated by Django 6.1.1 on 2026-09-17 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Cereals containing gluten'), ('crustaceans', 'Crustaceans'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('peanuts', 'Peanuts'), ('soy', 'Soybeans'), ('milk', 'Milk'), ('tree-nuts', 'Tree nuts'), ('celery', 'Celery'), ('mustard', 'Mustard'), ('sesame', 'Sesame'), ('sulphites', 'Sulphur dioxide and sulphites'), ('lupin', 'Lupin'), ('molluscs', 'Molluscs')], max_length=100), blank=True, default=list),
        ),
    ]
