# Generated by Django 6.1.1 on 2026-09-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_candyproduct_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candyproduct',
            constraint=models.CheckConstraint(condition=models.Q(('flaw__regex', '\\S')), name='candyproduct_flaw_is_not_blank', violation_error_message='Every candy must disclose a flaw (UC-06).'),
        ),
    ]
