# Generated by Django 6.1.1 on 2026-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_candyproduct_candy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
