# Generated by Django 6.1.1 on 2026-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_candy_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='image',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
