# Generated by Django 6.1.1 on 2026-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_candy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
