# Generated by Django 6.1.1 on 2026-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_candy_created_at_candy_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='candy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
