# Generated by Django 6.1.1 on 2026-09-17 14:14

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_candy_created_at_alter_candy_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candy',
            name='allergens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('gluten', 'Cereals containing gluten'), ('crustaceans', 'Crustaceans'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('peanuts', 'Peanuts'), ('soy', 'Soybeans'), ('milk', 'Milk'), ('tree-nuts', 'Tree nuts'), ('celery', 'Celery'), ('mustard', 'Mustard'), ('sesame', 'Sesame'), ('sulphites', 'Sulphur dioxide and sulphites'), ('lupin', 'Lupin'), ('molluscs', 'Molluscs')], max_length=20), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candy',
            name='sugar_content_g',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Grams of sugar per 100 g. Leave empty if unknown.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='candy',
            constraint=models.CheckConstraint(condition=models.Q(('sugar_content_g__isnull', True), models.Q(('sugar_content_g__gte', 0), ('sugar_content_g__lte', 100)), _connector='OR'), name='candy_sugar_per_100g_in_range', violation_error_message='Sugar per 100 g must be between 0 and 100.'),
        ),
    ]
