# Generated by Django 6.1.1 on 2026-09-17 18:53

# Additive. AddConstraint compiles to ALTER TABLE ... ADD CONSTRAINT ... CHECK,
# which PostgreSQL validates against every existing row -- the hazard
# docs/data-model.md records for migration 0003. Safe here because every slug
# comes from 0013 or from Candy.ensure_slug, and neither can produce a slug
# that is digits alone or empty. On a database that somehow holds one, this
# migration fails and changes nothing; find them with
#     SELECT id, name, slug FROM shop_candy WHERE slug !~ '\D';

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_candy_slug_required_and_names_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candy',
            constraint=models.CheckConstraint(condition=models.Q(('slug__regex', '\\D')), name='candy_slug_is_not_all_digits', violation_error_message='A slug needs a letter or a dash; digits alone read as a number.'),
        ),
    ]
