#!/usr/bin/env python
"""Enforce the ADR decisions that can be checked mechanically.

ADR 0003 defers Django REST Framework and names requirements.txt as where
compliance is visible, so that is a real check rather than prose in a document
nobody re-reads. ADR 0005's wish to keep the test stack small is deliberately
not checked here: it is a preference judged when a package is proposed, not a
number.

It also keeps the human-readable overview honest. The records under docs/
are the canonical version, written for agents; docs/overview.html is a short
plain-language page derived from them by hand. docs/overview.sources holds a
hash of each record as it stood when the page was last brought up to date, so
changing a record without revisiting the page fails here instead of leaving
the page quietly wrong. Stamping also embeds each record's text in the page,
between the RECORDS_START and RECORDS_END markers, so its "Full record" links
can show the Markdown formatted even when the page is opened from disk, where
a browser will not fetch the .md files.

Runs in CI (.github/workflows/ci.yml) and by hand:

    python scripts/adr_guards.py            # check
    python scripts/adr_guards.py --stamp    # after updating the overview page

Reads text files only -- no Django, no database, no installed dependencies --
so CI can run it as a job of its own that fails in seconds.
"""
import hashlib
import json
import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
MANIFEST = BASE_DIR / "requirements.txt"
DOCS_DIR = BASE_DIR / "docs"
SOURCES = DOCS_DIR / "overview.sources"
PAGE = DOCS_DIR / "overview.html"
RECORDS_START = "<!-- records:start"
RECORDS_END = "<!-- records:end -->"


def packages(manifest):
    """Requirement lines, with comments and blank lines stripped out."""
    lines = [
        line.split("#")[0].strip()
        for line in manifest.read_text(encoding="utf-8").splitlines()
    ]
    return [line for line in lines if line]


def canonical_docs(docs_dir=DOCS_DIR):
    """The records docs/overview.html summarises, as paths relative to docs_dir.

    Every ADR except the template, plus the requirements and the data model.
    A new ADR is picked up by the glob, so it cannot be left off the page by
    being left out of a list.
    """
    adrs = sorted(
        p for p in (docs_dir / "adr").glob("0*.md") if not p.name.startswith("0000-")
    )
    others = [docs_dir / "requirements.md", docs_dir / "data-model.md"]
    return [p.relative_to(docs_dir).as_posix() for p in adrs + others if p.exists()]


def digest(path):
    """sha256 of the file with line endings normalised.

    A Windows checkout with core.autocrlf has CRLF where CI's has LF; hashing
    raw bytes would make the two disagree about an unchanged file.
    """
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()[:16]


def records_block(docs_dir, rels):
    """The page's embedded copy of each record, as one JSON script element.

    Every "<" is escaped, so no record can close the element early -- a
    "</script>" inside an ADR would otherwise end it mid-string.
    """
    records = {
        rel: (docs_dir / rel).read_text(encoding="utf-8").replace("\r\n", "\n")
        for rel in rels
    }
    data = json.dumps(records, ensure_ascii=False, indent=0).replace("<", "\\u003c")
    return (
        f"{RECORDS_START} -- generated by `python scripts/adr_guards.py --stamp`; do not edit -->\n"
        f'<script type="application/json" id="records">{data}</script>\n'
        f"{RECORDS_END}"
    )


def embed_records(page, docs_dir, rels):
    """Replace the page's embedded records. False when the markers are missing."""
    html = page.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(RECORDS_START) + ".*?" + re.escape(RECORDS_END), re.S)
    if not pattern.search(html):
        return False
    block = records_block(docs_dir, rels)
    page.write_text(pattern.sub(lambda _: block, html), encoding="utf-8", newline="\n")
    return True


def stamp_docs(docs_dir=DOCS_DIR, sources=SOURCES, page=PAGE):
    """Record the current records as reflected in docs/overview.html."""
    rels = canonical_docs(docs_dir)
    if not embed_records(page, docs_dir, rels):
        print(f"{page.name} has no {RECORDS_START} ... {RECORDS_END} markers -- nothing stamped.")
        return 1
    lines = [f"{digest(docs_dir / rel)}  {rel}" for rel in rels]
    header = (
        "# Hashes of the records docs/overview.html was last updated against.\n"
        "# Regenerate with `python scripts/adr_guards.py --stamp`, and only\n"
        "# after updating the page and docs/README.md to match.\n"
    )
    sources.write_text(header + "\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"stamped {len(lines)} records into {sources.name} and {page.name}")
    return 0


def check_docs_sync(docs_dir=DOCS_DIR, sources=SOURCES):
    """Failures for records changed or added since the overview was updated."""
    if not sources.exists():
        return [f"{sources.name} is missing -- run `python scripts/adr_guards.py --stamp`."]

    recorded = {}
    for line in sources.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.startswith("#"):
            hash_, rel = line.split(maxsplit=1)
            recorded[rel] = hash_

    stale = [
        rel for rel in canonical_docs(docs_dir)
        if recorded.get(rel) != digest(docs_dir / rel)
    ]
    if not stale:
        return []
    return [
        "docs/overview.html is out of date with: " + ", ".join(stale) + ".\n"
        "  Update the page and the matching docs/README.md row, then run\n"
        "  `python scripts/adr_guards.py --stamp`."
    ]


def check(manifest=MANIFEST, docs_dir=DOCS_DIR, sources=SOURCES):
    print(f"$ adr-guards {manifest.name}", flush=True)
    if not manifest.exists():
        print(f"{manifest.name} is missing -- ADR 0003 cannot be checked.")
        return 1

    found = packages(manifest)
    failures = []

    drf = [p for p in found if p.lower().startswith("djangorestframework")]
    if drf:
        failures.append(
            f"ADR 0003 defers Django REST Framework, but requirements.txt has: {', '.join(drf)}.\n"
            "  Either drop it or supersede docs/adr/0003-backend.md."
        )

    failures += check_docs_sync(docs_dir, sources)

    for failure in failures:
        print(f"FAIL: {failure}")
    if failures:
        return 1

    print("ok: no DRF; docs/overview.html is current")
    return 0


if __name__ == "__main__":
    sys.exit(stamp_docs() if sys.argv[1:] == ["--stamp"] else check())
